"""
A case as a due-diligence dossier: the PDF a forwarder files, or hands a customs
officer, to show what was checked before a shipment moved or was held.

Why a forwarder needs this, and not only a risk score
-----------------------------------------------------
A customs broker carries the declarant's obligations. Vietnam's Customs Law
(54/2014/QH13, Art. 20(4)) says so in one line, and US export rules expect a
forwarder to know its customer (EAR Part 732, Supplement 3). When a shipment is
questioned later, "the model scored it 85" is not an answer anyone accepts. What
is accepted is a record: which checks ran, against which list and of what date,
what each found, who decided, and on what grounds. Every case already holds all
of that -- the findings, the screening snapshot, the agents' views, the gate's
receipts, the reviewer's decision. This module arranges it; it adds no judgement.

What it deliberately is not
---------------------------
Not generated by a model. The text below is the case's own fields plus a fixed
table of references, so nothing in the dossier can be a fresh confabulation at the
moment a person relies on it -- the same reason synthesise_packs() is code.

Not legal advice, and it says so on the page. The references say where an
obligation comes from; they do not say the obligation has been met.

The references are restricted to texts that were read, not recalled: each entry
in REFERENCES was checked against a fetched copy of the source on 2026-10-10.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

# --------------------------------------------------------------------------
# References
# --------------------------------------------------------------------------

REFERENCES: dict[str, dict[str, str]] = {
    "VN_CUSTOMS_LAW": {
        "cite": "Vietnam Customs Law No. 54/2014/QH13, Art. 18 and Art. 20(4)",
        "says": (
            "Art. 18 sets the rights and obligations of the customs declarant. "
            "Art. 20(4): a customs broker and its staff exercise the declarant's rights "
            "and obligations under Art. 18."
        ),
        "url": "https://luatvietnam.vn/xuat-nhap-khau/luat-hai-quan-2014-so-54-2014-qh13-87932-d1.html",
    },
    "VN_DECREE_259": {
        "cite": "Decree 259/2025/ND-CP on strategic trade control (effective 10 Oct 2025)",
        "says": (
            "Art. 3(2) defines dual-use goods as goods normally used for civilian purposes "
            "that can be used to develop, produce or use weapons; Arts. 7-9 cover the "
            "dual-use list, licensing and applications."
        ),
        "url": "https://luatvietnam.vn/xuat-nhap-khau/nghi-dinh-259-2025-nd-cp-ve-kiem-soat-thuong-mai-chien-luoc-414787-d1.html",
    },
    "VN_DECREE_169": {
        "cite": "Decree 169/2026/ND-CP on administrative penalties in the customs field (effective 1 Jul 2026)",
        "says": "Penalties for customs violations, including incorrect declarations.",
        "url": "https://luatvietnam.vn/thue/nghi-dinh-169-2026-nd-cp-quy-dinh-xu-phat-vi-pham-hanh-chinh-trong-linh-vuc-hai-quan-435022-d1.html",
    },
    "EAR_KYC": {
        "cite": "US EAR, 15 CFR Part 732, Supplement No. 3: 'Know Your Customer' Guidance and Red Flags",
        "says": (
            "Red flags include: 'The customer has little or no business background' (4); "
            "'A freight forwarding firm is listed as the product's final destination' (9); "
            "'The shipping route is abnormal for the product and destination' (10)."
        ),
        "url": "https://www.law.cornell.edu/cfr/text/15/appendix-Supplement_No_3_to_part_732",
    },
    "OFAC_SDN": {
        "cite": "OFAC Specially Designated Nationals List; UN Security Council Consolidated List",
        "says": "The lists this case was screened against, by name and by identifier.",
        "url": "https://www.treasury.gov/ofac/downloads/sdn.csv",
    },
    "INTERNAL": {
        "cite": "This forwarder's own screening policy",
        "says": "A tenant rule (blacklist, VIP registry, adverse-media screen), not a statute.",
        "url": "",
    },
}

# Public enforcement cases of the same shape, so a reviewer can see what the
# finding has meant when it was real. All are in data/public_cases.json.
PRECEDENTS: dict[str, dict[str, str]] = {
    "sanctions": {
        "what": "OFAC 2022: Toll Holdings, a freight forwarder, settled for USD 6.1M over shipments 'to, from, or through' DPRK, Iran and Syria.",
        "url": "https://ofac.treasury.gov/recent-actions/20220425",
    },
    "dual_use": {
        "what": "BIS 2023: US microcontrollers sent to a UAE free-zone consignee and on to Russian defence buyers (Temporary Denial Order).",
        "url": "https://www.govinfo.gov/content/pkg/FR-2023-11-14/html/2023-25005.htm",
    },
    "route": {
        "what": "BIS 2023: aircraft brakes consigned to a Maldives cargo agent, destination changed to Turkey after a forwarder raised concerns.",
        "url": "https://www.govinfo.gov/content/pkg/FR-2023-05-19/html/2023-10750.htm",
    },
    "origin": {
        "what": "EPPO 2024: Chinese aluminium foil declared as Myanmar origin to avoid EU anti-dumping duty.",
        "url": "https://www.eppo.europa.eu/media/news/germany-eppo-brings-charges-against-two-evading-anti-dumping-duties-aluminium-foil-imports-2024-07-29_en",
    },
    "value": {
        "what": "BIS 2022: an oscilloscope bought for about USD 25,000 declared 'Used' at USD 2,482, under the USD 2,500 filing threshold.",
        "url": "https://www.govinfo.gov/content/pkg/FR-2022-12-16/html/2022-27347.htm",
    },
    "classification": {
        "what": "EPPO 2024: finished steel sheets declared as semi-finished slabs to avoid anti-dumping duty.",
        "url": "https://www.eppo.europa.eu/media/news/spain-five-directors-two-companies-indicted-evading-anti-dumping-duties-steel-sheets-2024-09-24_en",
    },
}

# Finding-code prefix -> (references, precedent key, what the reviewer should obtain).
# Longest prefix wins, so HS_DESCRIPTION_MISMATCH_DUAL_USE is matched before
# HS_DESCRIPTION_MISMATCH.
FINDING_GUIDANCE: dict[str, tuple[tuple[str, ...], str | None, str]] = {
    "SANCTIONS_MATCH": (("OFAC_SDN", "VN_CUSTOMS_LAW"), "sanctions",
                        "Do not release. Confirm or rule out the match against the list entry's identifiers, and escalate to the compliance officer."),
    "SANCTIONS_SCREENING_UNAVAILABLE": (("OFAC_SDN",), "sanctions",
                                        "Re-run screening once the list is available. No screening is not a clearance."),
    "DUAL_USE_HS_CODE": (("VN_DECREE_259", "EAR_KYC"), "dual_use",
                         "Obtain the end-user statement and a licence determination for the goods before release."),
    "HS_DESCRIPTION_MISMATCH_DUAL_USE": (("VN_DECREE_259", "VN_CUSTOMS_LAW"), "dual_use",
                                         "Ask for the technical specification; the goods described may be controlled under a heading other than the one declared."),
    "HS_DESCRIPTION_MISMATCH": (("VN_CUSTOMS_LAW", "VN_DECREE_169"), "classification",
                                "Ask the shipper to confirm the classification against the goods; a wrong heading is the declarant's liability."),
    "HS_CODE": (("VN_CUSTOMS_LAW",), "classification", "Obtain a valid HS heading from the shipper."),
    "HIGH_RISK_DESTINATION": (("OFAC_SDN", "EAR_KYC"), "sanctions",
                              "Enhanced due diligence on the consignee and end use before release."),
    "HIGH_RISK_ORIGIN": (("OFAC_SDN", "VN_CUSTOMS_LAW"), "origin",
                         "Verify the certificate of origin and the producer; a false origin is a known way around duties and sanctions."),
    "HIGH_RISK_TRANSIT": (("OFAC_SDN", "EAR_KYC"), "sanctions",
                          "Confirm the routing is necessary and that no party in the transit country is involved."),
    "MULTIPLE_DIVERSION_HUBS": (("EAR_KYC",), "route", "Ask why the routing passes through several transhipment hubs."),
    "ROUTE_CHANGED_AFTER_BOOKING": (("EAR_KYC",), "route", "Ask who changed the destination and why, in writing."),
    "SHIPPER": (("EAR_KYC",), None, "Verify the shipper's registration and trading history."),
    "RECENTLY_REGISTERED_SHIPPER": (("EAR_KYC",), None, "Verify the shipper's registration and trading history."),
    "FREIGHT": (("VN_CUSTOMS_LAW", "VN_DECREE_169"), "value", "Reconcile the freight charge with the lane and the goods."),
    "VALUE_DENSITY": (("VN_CUSTOMS_LAW", "VN_DECREE_169"), "value", "Obtain the commercial invoice and check the declared value against the goods."),
    "BLACKLIST": (("INTERNAL",), None, "The shipper is on this forwarder's blacklist; release needs an explicit override."),
    "WHITELIST_IDENTITY_MISMATCH": (("INTERNAL", "EAR_KYC"), None, "A registered tax ID is presented under another company's name; verify identity."),
    "ZERO_DAY": (("INTERNAL", "EAR_KYC"), None, "Read the adverse-media sources cited and decide whether they concern this party."),
    "EXPOSURE_CLAIM_UNSUPPORTED": (("INTERNAL",), None, "Disregard the model's exposure figure; it was not supported by the case."),
}


def guidance_for(code: str) -> tuple[tuple[str, ...], str | None, str]:
    """References, precedent key and the action for a finding code."""
    best = ""
    for prefix in FINDING_GUIDANCE:
        if code.startswith(prefix) and len(prefix) > len(best):
            best = prefix
    if best:
        return FINDING_GUIDANCE[best]
    return (("INTERNAL",), None, "Review the finding detail.")


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def _ascii(text: Any) -> str:
    """The built-in PDF fonts are Latin-1; see document_render._ascii."""
    replacements = {"\u2011": "-", "\u2013": "-", "\u2014": "-", "\u2019": "'", "\u201c": '"', "\u201d": '"'}
    out = str(text if text is not None else "")
    for src, dst in replacements.items():
        out = out.replace(src, dst)
    return out.encode("latin-1", "replace").decode("latin-1")


def _money(value: Any) -> str:
    try:
        return f"USD {float(value):,.0f}"
    except (TypeError, ValueError):
        return "-"


def dossier_findings(case: dict[str, Any]) -> list[dict[str, Any]]:
    """The findings with their references attached. Exposed for tests and the API."""
    out = []
    for finding in (case.get("validation") or {}).get("findings") or []:
        code = str(finding.get("code") or "")
        refs, precedent, action = guidance_for(code)
        out.append({
            "code": code,
            "severity": finding.get("severity"),
            "floor": finding.get("floor"),
            "detail": finding.get("detail"),
            "references": list(refs),
            "precedent": precedent,
            "action": action,
        })
    order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
    out.sort(key=lambda f: (order.get(str(f["severity"]), 9), -(f["floor"] or 0)))
    return out


def render_dossier(case: dict[str, Any], generated_by: str | None = None) -> bytes | None:
    """The dossier as PDF bytes, or None when the PDF library is unavailable."""
    try:
        from fpdf import FPDF
    except Exception:  # noqa: BLE001
        return None

    shipment = case.get("shipment") or {}
    validation = case.get("validation") or {}
    reconciliation = case.get("reconciliation") or {}
    decision = case.get("decision") or {}
    findings = dossier_findings(case)
    snapshot = validation.get("sanctions_snapshot") or {}
    screening = validation.get("sanctions_screening")

    pdf = FPDF(unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_title(_ascii(f"Due-diligence dossier {case.get('case_id')}"))
    pdf.set_author("Floorline")
    pdf.add_page()
    width = 210 - pdf.l_margin - pdf.r_margin

    def heading(text: str) -> None:
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, _ascii(text.upper()), new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(190, 190, 190)
        pdf.line(pdf.l_margin, pdf.get_y(), 210 - pdf.r_margin, pdf.get_y())
        pdf.ln(1.5)

    def row(label: str, value: Any, bold: bool = False) -> None:
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(90, 90, 90)
        pdf.cell(56, 5.5, _ascii(label))
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "B" if bold else "", 9.5)
        pdf.multi_cell(0, 5.5, _ascii(value if value not in (None, "") else "-"), new_x="LMARGIN", new_y="NEXT")

    def para(text: str, size: float = 9, grey: bool = False) -> None:
        pdf.set_font("Helvetica", "", size)
        if grey:
            pdf.set_text_color(110, 110, 110)
        else:
            pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(width, 4.6, _ascii(text), new_x="LMARGIN", new_y="NEXT")

    # ---- title -----------------------------------------------------------
    pdf.set_font("Helvetica", "B", 15)
    pdf.cell(0, 9, "DUE-DILIGENCE DOSSIER", new_x="LMARGIN", new_y="NEXT")
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    para(
        f"Case {case.get('case_id')}, shipment {case.get('shipment_id')}. Generated {stamp}"
        + (f" for {generated_by}" if generated_by else "")
        + ". Assembled by code from the case record. The only text written by a language "
        "model is the agents' own conclusions, under Specialist views, quoted as the agents "
        "gave them when the case ran. It records what was checked and decided; it is not "
        "legal advice and not a customs declaration.",
        grey=True,
    )

    # ---- outcome ---------------------------------------------------------
    heading("Outcome")
    row("State", case.get("state"), bold=True)
    row("Effective risk", f"{reconciliation.get('effective_risk', case.get('risk_score'))}/100"
        f" (rules floor {reconciliation.get('risk_floor', validation.get('risk_floor'))},"
        f" model {reconciliation.get('model_risk', case.get('model_risk_score'))})")
    row("Score source", reconciliation.get("source"))
    row("Auto-clear permitted", "yes" if reconciliation.get("auto_clear_permitted") else "no")
    if decision:
        by_human = decision.get("decided_by") == "human"
        row("Decided by", "a person" if by_human else "agent, within its published boundary")
        row("Outcome", decision.get("outcome"))
        row("Rationale" if by_human else "Rationale (agent)", decision.get("rationale"))
    receipts = [a for a in case.get("actions") or [] if a.get("status") in ("done", "denied")]
    for action in receipts[:6]:
        detail = action.get("detail") or {}
        row(f"Action: {action.get('action')}",
            f"{action.get('status')}"
            + (f" - {detail.get('gate_reason')}" if detail.get("gate_reason") else "")
            + (f" (boundary v{detail.get('boundary_version')})" if detail.get("boundary_version") else ""))

    # ---- shipment --------------------------------------------------------
    heading("Shipment as declared")
    for label, key in (
        ("Shipper", "shipper_company"), ("Shipper country", "shipper_country"),
        ("Shipper tax ID", "shipper_tax_id"), ("Receiver", "receiver_company"),
        ("Receiver country", "receiver_country"), ("Consignee", "consignee_name"),
        ("Origin", "origin"), ("Destination", "destination"), ("Route", "route_details"),
        ("Transit", "transit_points"), ("Goods", "cargo_description"), ("HS code", "hs_code"),
    ):
        if shipment.get(key) not in (None, ""):
            row(label, shipment.get(key))
    row("Declared value", _money(shipment.get("declared_value")))
    row("Weight", f"{shipment.get('weight_kg')} kg" if shipment.get("weight_kg") else None)
    row("Freight", _money(shipment.get("shipping_cost")))

    # ---- sanctions -------------------------------------------------------
    heading("Sanctions screening")
    row("Result", screening or "not recorded", bold=True)
    row("List", snapshot.get("source"))
    row("List version", snapshot.get("version"))
    row("List synced", snapshot.get("synced_at") or "unknown")
    row("Entities screened against", snapshot.get("entity_count"))
    if snapshot.get("source") == "bundled_seed":
        para("This case was screened against the bundled demonstration seed list, "
             "which is synthetic. It is not evidence of screening against an official list.",
             grey=True)

    # ---- findings --------------------------------------------------------
    heading(f"Findings ({len(findings)})")
    if not findings:
        para("No deterministic finding was raised.")
    for f in findings:
        pdf.set_font("Helvetica", "B", 9.5)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(width, 5.2, _ascii(f"[{f['severity']}] {f['code']}  (floor {f['floor']})"),
                       new_x="LMARGIN", new_y="NEXT")
        para(str(f["detail"] or ""))
        para("Action: " + f["action"])
        para("Basis: " + "; ".join(REFERENCES[r]["cite"] for r in f["references"]), grey=True)
        if f["precedent"]:
            para("Comparable public case: " + PRECEDENTS[f["precedent"]]["what"], grey=True)
        pdf.ln(1.5)

    observations = validation.get("observations") or []
    if observations:
        para("Recorded but not scored: " + "; ".join(
            f"{o.get('code')} - {o.get('detail')}" for o in observations[:5]), size=8.5, grey=True)

    # ---- specialist views ------------------------------------------------
    heading("Specialist views")
    para("What each agent concluded, quoted as it was recorded, beside the rules' view. "
         "Agent output is advisory: it can raise the rules floor above, never lower it.", grey=True)
    from vf_logistics.orchestrator import synthesise_packs

    for pack in synthesise_packs(case):
        row(pack["pack"], f"(agent) {pack['headline']}" if pack["pack"] == "Exposure and counterparty" else pack["headline"])
        if pack.get("disagreement"):
            para("The agent and the rules disagree on this pack.", grey=True)

    # ---- references ------------------------------------------------------
    heading("References")
    used = sorted({r for f in findings for r in f["references"]} | {"VN_CUSTOMS_LAW"})
    for key in used:
        ref = REFERENCES[key]
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(width, 4.6, _ascii(ref["cite"]), new_x="LMARGIN", new_y="NEXT")
        para(ref["says"], size=8.5)
        if ref["url"]:
            para(ref["url"], size=8, grey=True)
        pdf.ln(1)
    precedents = sorted({f["precedent"] for f in findings if f["precedent"]})
    for key in precedents:
        para(PRECEDENTS[key]["what"], size=8.5)
        para(PRECEDENTS[key]["url"], size=8, grey=True)

    # ---- provenance ------------------------------------------------------
    heading("Provenance")
    agents = [s.get("agent") for s in case.get("steps") or [] if s.get("agent")]
    row("Agents that ran", ", ".join(agents) if agents else "none (decided by rules)")
    row("Model calls", case.get("_agent_calls"))
    row("Model cost", f"USD {float(case.get('_estimated_cost_usd') or 0):.4f}")
    row("Case created", case.get("created_at"))
    row("Last updated", case.get("updated_at"))
    row("Source", case.get("source"))

    return bytes(pdf.output())
